env:
  browser: true
  es2020: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - plugin:react-hooks/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  indent: ["error", 2]
  quotes: ["error", "double"]
  react/prop-types: [0]
  react-hooks/exhaustive-deps: [0]